### ISSUE TITLE
How to support python 3.6?

### ISSUE THREAD

**Issue by Lucienxhh** [ctnava/tiktoken-offline#1]
Information may be useful:
1. [offline tiktoken](https://stackoverflow.com/questions/76106366/how-to-use-tiktoken-in-offline-mode-computer)
2. [support for python 3.8](https://github.com/openai/tiktoken/pull/14)

**Comment by ctnava** [comment]
So, the first issue has already been resolved. I have all of this data cached already under [data](https://github.com/ctnava/tiktoken-offline/tree/main/tiktoken_offline/data).

**Comment by ctnava** [comment]
If you have the time before I do, can you see if just changing the version number in [setup](https://github.com/ctnava/tiktoken-offline/blob/main/setup.py) works? I really don't think that 3.6 support is necessary in this context because GPT-4's ADA feature runs on Python 3.8 ([shown here](https://chat.openai.com/share/f4031ba5-eaac-4124-ace9-af0d8e3217e9)). Is there a reason you specifically need this? If there is, I don't mind doing it myself.

**Comment by ctnava** [comment]
Two issues have been opened if you would like to provide insight:

- [Slight Inaccuracy for Byte Pair Encoding ](https://github.com/ctnava/tiktoken-offline/issues/2)
- [Regex Requirement](https://github.com/ctnava/tiktoken-offline/issues/3)
